/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class blog_zero_com_mp3encoder_Mp3Encoder */

#ifndef _Included_blog_zero_com_mp3encoder_Mp3Encoder
#define _Included_blog_zero_com_mp3encoder_Mp3Encoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     blog_zero_com_mp3encoder_Mp3Encoder
 * Method:    encode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_blog_zero_com_mp3encoder_Mp3Encoder_encode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
